name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      API_TOKEN: 1234
      APP_PORT: :3000
      CHROME_BIN: chrome

    steps:
    - uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - run: |
        echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
        chrome --version
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          *.png
          *.log
